"""added invitation token

Revision ID: 15214ba9c85a
Revises: 230b5ebebdd7
Create Date: 2024-08-10 22:40:55.899525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15214ba9c85a'
down_revision = '230b5ebebdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('invitation_token')

    # ### end Alembic commands ###
