"""migrations

Revision ID: 272c14088b7b
Revises: 90a4fb2e60e3
Create Date: 2024-08-11 23:29:13.988978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272c14088b7b'
down_revision = '90a4fb2e60e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'])

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint('stores_merchant_id_fkey', type_='foreignkey')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('stores_merchant_id_fkey', 'merchants', ['merchant_id'], ['id'])

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
