"""added invitation token column

Revision ID: 6b916e3529e2
Revises: 15214ba9c85a
Create Date: 2024-08-11 02:32:11.561686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b916e3529e2'
down_revision = '15214ba9c85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.drop_column('invitation_token')

    # ### end Alembic commands ###
