"""updated profilePictures

Revision ID: d26b55f64717
Revises: 4373f1784cf7
Create Date: 2024-08-19 05:31:29.607114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26b55f64717'
down_revision = '4373f1784cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePicture', sa.String(), nullable=True))

    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePicture', sa.String(), nullable=True))

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePicture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_column('profilePicture')

    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.drop_column('profilePicture')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('profilePicture')

    # ### end Alembic commands ###
