"""migrations

Revision ID: e511f4dd376c
Revises: 272c14088b7b
Create Date: 2024-08-11 23:38:38.545157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e511f4dd376c'
down_revision = '272c14088b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint('merchants_store_id_fkey', type_='foreignkey')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'merchants', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('merchants_store_id_fkey', 'stores', ['store_id'], ['id'])

    # ### end Alembic commands ###
