"""added foreign_key

Revision ID: ee2ff55e3c91
Revises: 13db61cb1721
Create Date: 2024-08-08 23:23:41.882726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2ff55e3c91'
down_revision = '13db61cb1721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesReports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clerk_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clerks', ['clerk_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesReports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('clerk_id')

    # ### end Alembic commands ###
